import React from 'react';


const About = () => {
    return (
    <div>
        <h1>About Page !</h1>
        <h2>My Breve history</h2>
        <p>
            This is the hystory of my life ...
            This is the hystory of my life ...
            This is the hystory of my life ...
            This is the hystory of my life ...
        </p>
        <p>
            This is the hystory of my life ...
            This is the hystory of my life ...
            This is the hystory of my life ...
            This is the hystory of my life ...
        </p>
        <p>
            This is the hystory of my life ...
            This is the hystory of my life ...
            This is the hystory of my life ...
            This is the hystory of my life ...
        </p>
        
    </div>)
}

export default About;